#!/usr/bin/env python3
"""Regenerate auto-managed sections of memory/STATUS.md.

Tool-agnostic: invoked from a GitHub Action on push to main, but also works
locally (`python3 scripts/regen-status.py`).

Auto-managed (overwritten between BEGIN_AUTO/END_AUTO markers):
  - LAST_UPDATED          ISO date stamp
  - RECENTLY_COMPLETED    last 15 merged PRs from `gh pr list`
  - OPEN_PRS              currently open PRs from `gh pr list`

Hand-edited (preserved verbatim):
  - Active Work
  - Blocked
  - Environment Notes

Requires `gh` on PATH and a valid auth token (GH_TOKEN env var on Actions).
"""

import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
STATUS_PATH = REPO_ROOT / "memory" / "STATUS.md"

MERGED_LIMIT = 15
OPEN_LIMIT = 20


def gh_json(args: list[str]) -> list[dict]:
    """Run `gh` and return parsed JSON; empty list on failure."""
    try:
        out = subprocess.check_output(["gh", *args], text=True, stderr=subprocess.PIPE)
        return json.loads(out) if out.strip() else []
    except subprocess.CalledProcessError as e:
        # Surface gh's stderr — the most useful diagnostic when running in CI.
        stderr = (e.stderr or "").strip()
        print(f"gh call failed (exit {e.returncode}): {' '.join(['gh', *args])}", file=sys.stderr)
        if stderr:
            print(f"  stderr: {stderr}", file=sys.stderr)
        return []
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"gh call failed: {e}", file=sys.stderr)
        return []


def fetch_merged_prs() -> list[dict]:
    return gh_json([
        "pr", "list",
        "--state", "merged",
        "--limit", str(MERGED_LIMIT),
        "--json", "number,title,mergedAt,author",
    ])


def fetch_open_prs() -> list[dict]:
    return gh_json([
        "pr", "list",
        "--state", "open",
        "--limit", str(OPEN_LIMIT),
        "--json", "number,title,headRefName,isDraft,author",
    ])


def fmt_merged(prs: list[dict]) -> str:
    if not prs:
        return "_(no merged PRs found)_"
    lines = []
    for pr in prs:
        merged = pr.get("mergedAt", "")[:10]  # YYYY-MM-DD
        author = (pr.get("author") or {}).get("login", "?")
        lines.append(f"- **PR #{pr['number']}** — {pr['title']} _(merged {merged} by @{author})_")
    return "\n".join(lines)


def fmt_open(prs: list[dict]) -> str:
    if not prs:
        return "_(no open PRs)_"
    # Suppress dependabot noise from the headline list — they're easy to enumerate via gh.
    human = [p for p in prs if (p.get("author") or {}).get("login") != "app/dependabot"]
    bot_count = len(prs) - len(human)
    lines = []
    for pr in human:
        draft = " _(draft)_" if pr.get("isDraft") else ""
        author = (pr.get("author") or {}).get("login", "?")
        lines.append(f"- **#{pr['number']}** — {pr['title']} `{pr['headRefName']}` (@{author}){draft}")
    if bot_count:
        lines.append(f"- _+{bot_count} dependabot PR{'s' if bot_count != 1 else ''} not shown_")
    return "\n".join(lines) if lines else "_(only dependabot PRs open)_"


def replace_block(text: str, marker: str, replacement: str) -> str:
    """Replace content between <!-- BEGIN_AUTO:MARKER --> and <!-- END_AUTO:MARKER -->."""
    pattern = re.compile(
        rf"(<!-- BEGIN_AUTO:{marker} -->)(.*?)(<!-- END_AUTO:{marker} -->)",
        re.DOTALL,
    )
    if not pattern.search(text):
        print(f"warning: marker {marker} not found in STATUS.md", file=sys.stderr)
        return text
    return pattern.sub(rf"\1\n{replacement}\n\3", text)


def main() -> int:
    if not STATUS_PATH.exists():
        print(f"error: {STATUS_PATH} does not exist", file=sys.stderr)
        return 1

    original = STATUS_PATH.read_text()

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    merged_prs = fetch_merged_prs()
    open_prs = fetch_open_prs()

    updated = original
    updated = replace_block(updated, "LAST_UPDATED", f"> Last updated: {today} _(auto-regenerated by `scripts/regen-status.py`)_")
    updated = replace_block(updated, "RECENTLY_COMPLETED", fmt_merged(merged_prs))
    updated = replace_block(updated, "OPEN_PRS", fmt_open(open_prs))

    if updated == original:
        print("STATUS.md unchanged")
        return 0

    STATUS_PATH.write_text(updated)
    print(f"STATUS.md regenerated ({len(merged_prs)} merged, {len(open_prs)} open)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
